<<<<<<< HEAD
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
branches:
  only:
    - master
=======
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
branches:
  only:
    - master
>>>>>>> origin
